export const freeContent = {
	'angular': [
		'basics-anatomy-of-angular',
		'basics-cli',
		'basics-components',
		'basics-modules',
		'basics-resources',
		'basics-services',
		'start-angular-beginner-tutorial',
	],
	'cloud-functions': [
		'auth-async-await',
		'auth-function',
		'auth-intro',
		'auth-testing',
		'callable-frontend',
		'callable-intro',
		'callable-sms',
		'firestore-intro',
		'firestore-oncreate',
		'firestore-onupdate',
		'http-basic',
		'http-expressjs',
		'http-intro',
		'http-middleware',
		'intro-course-resources',
		'intro-deployment',
		'intro-project-structure',
		'intro-setting-up-firebase-cloud-functions',
		'intro-what-is-serverless',
		'outro-pro-tips',
		'storage-gcp',
		'storage-intro',
		'storage-resizer'
	],
	'dart': [
		'basics-dart-100-seconds',
		'basics-null-safety',
	],
	'firebase-security': [
		'intro-firebase-security-100-seconds',
		'testing-report',
	],
	'firestore-data-modeling': [
		'basics-read-documents',
		'bonus-top-five',
		'relational-cardinality',
	],
	'flutter-firebase': [
		'basic-training',
		'intro-flutter-100s',
		'project-demo-app-tour',
	],
	'flutter-firebase-v1': [
		'intro-resources',
		'project-auth-apple-signin',
		'project-demo-app-tour',
		'vs-code-pro-tips',
	],
	'git': [
		'advanced-actions',
		'advanced-bonus-tips',
		'basics-init',
		'basics-install',
		'basics-what-is-git',
		'collab-pull-request',
	],
	'ionic': [
		'basics-code-organization',
		'intro-resources',
		'intro-what-ionic',
	],
	'javascript': [
		'beginner-js-functions',
		'beginner-js-objects',
		'beginner-js-survival-guide',
		'beginner-js-where-to-run',
		'concepts-console',
		'concepts-modules',
		'deno-basics',
		'interview-graphs',
		'intro-history',
		'intro-how-js-works',
		'node-basics',
	],
	'js': [
		'101-basics',
		'101-js-in-100-seconds',
		'102-prototype-chain',
		'bonus-haters',
	],
	'nextjs': [
		'basics-authjs',
		'basics-next-100s',
		'basics-prisma',
		'basics-seo',
	],
	'react': [],
	'react-next-firebase': [
		'app-technical-overview',
		'intro-firebase-basics',
		'intro-next-basics',
		'intro-react-basics',
		'intro-resources',
		'ssr-next-seo',
	],
	'stripe-js': [
		'intro-node-setup',
		'intro-resources',
		'intro-rest',
		'intro-stripe-api-keys',
		'intro-what-is-stripe',
	],
	'supabase': [
		'intro-react-basics',
		'intro-supabase-basics',
		'intro-supbase-100-seconds',
		'intro-zack',
		'setup-repo',
		'setup-supabase',
	],
	'sveltekit': [
		'basics-devtools',
		'basics-routing',
		'basics-setup',
		'basics-svelte-100s',
		'setup-tour',
	],
	'vscode-tricks': [
		'basics-cli',
		'basics-cmd-palette',
		'basics-explorer',
		'basics-intellisense',
		'basics-keyboard-shortcuts',
		'basics-settings',
		'tip-auto-dir',
		'tip-hints',
		'tip-move-fast',
		'vscode-100-seconds',
	],
	'vue': [
		'auth-state',
		'intro-routing',
		'intro-vue',
	],
};
